//
// This code is generated by export_aseprite.js
// Don't edit by hand. Or do, it's your life, I don't care.
//

import { Rectangle } from "../geometry/Rectangle";
import { AnimationData } from "./AnimationData";

export class TexturePaths
{
	public static readonly CHARACTER: string = "assets/character.png";
	public static readonly COLLECTABLES: string = "assets/collectables.png";
	public static readonly NECKY: string = "assets/necky.png";
}